baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'mnml'

[params]
test1 = 'test1'
showProposeEdit = false
proposeEditRepos = ''
proposeEditLabel = 'Propose edits on GitHub'
proposeEditContentDir = 'content'
proposeEditTarget = '_blank'

[params.workaround]
deeplInputControllerMargin = false

[params.fonts]
fontFamily = 'Helvetica, Arial, "Noto Sans", sans-serif'

[params.fonts.serif]
fontFamily = 'Georgia, "Times New Roman", "Noto Serif", serif'

[params.fonts.monospace]
fontFamily = '"SF Mono", Consolas, "DejaVu Sans Mono", "Roboto Mono", "Courier New", monospace'

[params.fonts.google]
url = ""

[pagination]
path = "/"

[module]

[module.hugoVersion]
extended = false
min = "0.133.0"
[[module.imports]]
path = 'github.com/2b3d4f/hugo-module-host-gfonts-local'
