baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'mnml'

[params]
test1 = 'test1'
showProposeEditOn = false
proposeEditRepos = ''
proposeEditLabel = 'Propose edits on GitHub'
proposeEditContentDir = 'content'
proposeEditTarget = '_blank'

[params.workaround]
deeplInputControllerMargin = false

[params.style]
fontFamily = 'Helvetica, Arial, "Noto Sans", sans-serif'

[params.googleFonts]
path = ""

[pagination]
path = "/"

[module]

[module.hugoVersion]
extended = false
min = "0.133.0"
