baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'mnml'

[params]
test1 = 'test1'
    [params.workaround]
    deeplInputControllerMargin = false
    [params.style]
    fontFamily = 'Helvetica, Arial, Roboto, "Noto Sans", sans-serif'

[pagination]
path = "/"

[module]

[module.hugoVersion]
extended = false
min = "0.133.0"
