baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'mnml'

[params]

[params.fonts]
fontFamily = 'Helvetica, Arial, "Noto Sans", sans-serif'

[params.fonts.serif]
fontFamily = 'Georgia, "Times New Roman", "Noto Serif", serif'

[params.fonts.monospace]
fontFamily = '"SF Mono", Consolas, "DejaVu Sans Mono", "Roboto Mono", "Courier New", monospace'

[params.fonts.google]
url = ""

[params.content] # Settings in params.content can be overridden by front matter
showEditOn = false
editOnRepos = ''
editOnLabel = 'Propose edits on GitHub'
editOnContentDir = 'content'
editOnTarget = '_blank'

[params.footer]
showThemeBy = true
showBuiltWith = true

[params.workaround]
deeplInputControllerMargin = false

[pagination]
path = "/"

[module]

[module.hugoVersion]
extended = false
min = "0.133.0"
[[module.imports]]
path = 'github.com/2b3d4f/hugo-module-host-gfonts-local'
